spring:
  application:
    name: etf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      leak-detection-threshold: 0
      connection-init-sql: SET statement_timeout = 0 # 제한 해제 (대량 배치 작업을 위해 타임아웃 끔)
  batch:
    jdbc:
      initialize-schema: always
    schema: classpath:/org/springframework/batch/core/schema-postgresql.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
  codec:
    max-in-memory-size: 10485760

api:
  service-key: ${SERVICE_KEY}
  base-url: https://apis.data.go.kr/1160100/service/GetSecuritiesProductInfoService/getETFPriceInfo

scheduler:
  etf:
    cron: "0 32 18 * * ?"