spring:
  application:
    name: etf
  profiles:
    include: secret
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: org.postgresql.Driver
    # URL 구조와 공통 옵션은 여기서 관리 (Git 공유 됨)
    # 접속 정보는 secret 파일의 변수(${secret.db...})로 주입받음
    url: jdbc:postgresql://${secret.db.host}:${secret.db.port}/${secret.db.name}?prepareThreshold=0&reWriteBatchedInserts=true
    username: ${secret.db.username}
    password: ${secret.db.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      leak-detection-threshold: 0
      connection-init-sql: SET statement_timeout = 0
  batch:
    jdbc:
      initialize-schema: always
    schema: classpath:/org/springframework/batch/core/schema-postgresql.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
  codec:
    max-in-memory-size: 10485760

api:
  service-key: ${secret.api.service-key}
  base-url: https://apis.data.go.kr/1160100/service/GetSecuritiesProductInfoService/getETFPriceInfo

scheduler:
  etf:
    cron: "0 0 9 * * ?"

# Actuator 설정 (모니터링)
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
